### ISSUE TITLE
EOL "¬" is not being removed once we enable the show-invisibles

### ISSUE THREAD

**Issue by jayudhandha** [coderaiser/cm-show-invisibles#11]
Hi,

I am enabling show-invisibles using toggle button in my app.

The "." are working fine and being added/removed on button click.

But EOL "¬" is not being removed once appeared. 

Is it issue or something i need to do at my end?

Thanks,
Jayesh

**Comment by coderaiser** [comment]
That's by design,  "¬" symbol shows you where line is ended, so it can't be removed.
