### ISSUE TITLE
add a min-count for spaces & treat spaces at line-start differently ?

### ISSUE THREAD

**Issue by Asc2011** [coderaiser/cm-show-invisibles#6]
I wonder if it would visually be more attractive to add the middle-point only if there are at least two consecutive spaces. Could be nice, since typically one space in between code-words is ok but if more spaces are in sequence, then it would be nice to get a visual hint (before the linter barks) ? I've reduced the visual intensity of the middle-points using a opacity: 0.2.
The indentation-spaces at the beginning of a line are ok, if the number matches the configured indentation-setting. Maybe just display the middle-points in case the numbers don't match. E.g. if one works with soft-tab-setting of 4 and at the beginning of the line there are 3- or 9- instead of 4- and 8-spaces then the middle-dots would show up ?
I solely work with indentation-based scripting-langs like coffee and python. So these visual-clues are important to me.
And maybe add your nice addon into codemirror/addon/display or anywhere else you find it fits best.

thx Andreas

**Comment by coderaiser** [comment]
Could you please provide your use case (maybe with screenshots). I don't quite understand what are you talking about.

**Comment by Asc2011** [comment]
Sure.

case-2, given the CodeMirrors tabSize is set to 2

a function like so
```
fn = (val) ->
  return val
```
![image](https://user-images.githubusercontent.com/829435/29263630-f597febc-80d9-11e7-9df0-4c5ad170e678.png)

Shows the dots as expected. In this situation i don't need any of them. But if there are 3-spaces/dots or in front of the return, that is an error.
![image](https://user-images.githubusercontent.com/829435/29263732-57a8d360-80da-11e7-94fe-f87359e34d22.png)
A proper linter will spot and mark it as 'inconsistent indentation' - as you can see in the screenshot.
I'd like to remove that linter-rule and have the visual feedback as dots.

Same with two consecutive spaces after the equal-sign
![image](https://user-images.githubusercontent.com/829435/29263981-83399eb4-80db-11e7-8fb9-894032c60a39.png)
That is not an error. But smth. i'd like to get visual-feedback for,  like so
![image](https://user-images.githubusercontent.com/829435/29264180-54fa6e92-80dc-11e7-90a5-27e8536afaab.png)
So only display dots in case of two consecutive spaces or a misaligned indent. Trailing spaces(at the end of a line) should always be dotted.
![image](https://user-images.githubusercontent.com/829435/29264366-15a5cd3a-80dd-11e7-8505-aea9f1eba990.png)
The linter marked this as an error. I'd prefer dots instead of an error.

**Comment by coderaiser** [comment]
It is an interesting idea for a pull request :). So you want superfluous dots looks different? Different color, for example?

**Comment by Asc2011** [comment]
well, almost. I'd like them to disappear for all 'normal'-cases. So dots should only become visible

1. if the indentation is wrong or 
2. if two consecutive spaces surrounded by code-fragments are detected or 
3. if one or more trailing-spaces are found at the end of the line.

Maybe i'll try this myself. Detection of a indentation-mismatch is complicated. A simple solution would just divide the count of leading-spaces by the tabSize-setting. So 7 by 2 must be wrong. The linter compares the indent of the previous line with the current. I'm not sure if that is doable with the CM token-stream.

**Comment by coderaiser** [comment]
Closed due to long time of inactivity
