### ISSUE TITLE
What about tabs (and maybe other non-printables we're missing)?

### ISSUE THREAD

**Issue by elmigranto** [coderaiser/cm-show-invisibles#7]
Hi, and first of all, thanks for a neat plugin, proved really useful and saved me quite some time digging in CM internals! ❤️

I am wondering how hard would it be to add support for displaying tabs (`\t`). There is CM option to consider, but since you render CSS pragramatically, maybe we can use box characters to draw lines of appropriate length.

Thanks for your help.

**Comment by elmigranto** [comment]
On a sidenote, I am also wondering if it would be possible to distinguish between LF (`\n`) vs CRLF (`\r\n`), perhaps with CSS?

And speaking of CSS, what's the reason behind inserting it with JS, wouldn't it be possible to overlay every, say, space with single span of certain CSS class, why we need number of repetions? Would be great to be able to define which invisibles get replaces with which character via CodeMirror options, but doesn't seem to be possible; even with CSS one would have to be wierd with selectors.

What do you think? @coderaiser
(I can file another issues for this, if you'd prefer that.)

**Comment by coderaiser** [comment]
> I am wondering how hard would it be to add support for displaying tabs (\t). There is CM option to consider, but since you render CSS pragramatically, maybe we can use box characters to draw lines of appropriate length.

What the reason if `codemirror` supports this already? 

> On a sidenote, I am also wondering if it would be possible to distinguish between LF (\n) vs CRLF (\r\n), perhaps with CSS?

I have no idea :). As I know internally `codemirror` does not distinguish them, in [dword](https://github.com/cloudcmd/dword) I get `separator` and then on `getValue` just use it with [codemirror's getValue](https://codemirror.net/doc/manual.html#api_content)

> And speaking of CSS, what's the reason behind inserting it with JS, wouldn't it be possible to overlay every, say, space with single span of certain CSS class, why we need number of repetitions?

The thing is `codemirror` doesn't create `html` elements for `spaces`, so this solution need to show line endings. Here is [answer of Marijn Haverbeke](https://stackoverflow.com/questions/19246539/is-it-possible-to-show-hidden-characters-in-codemirror), `codemirror's` author.

**Comment by elmigranto** [comment]
> What the reason if codemirror supports this already?

Oh, really? Do you know which option to set, I kind of assumed since there were no way to display spaces, same was true for tabs.

**Comment by coderaiser** [comment]
You just said that.
> There is CM option to consider

I do not use tabs, so didn't dig in.
[Here is demo with tabs](https://codemirror.net/demo/visibletabs.html) anyways.

**Comment by elmigranto** [comment]
I meant CM option for tab width.

**Comment by coderaiser** [comment]
It is a good idea for a pull request :), if you use them.

**Comment by elmigranto** [comment]
Alright, will try to take look at it!

**Comment by coderaiser** [comment]
Closed due to long time of inactivity

**Comment by twwwt** [comment]
Even considering the fact that CodeMirror already provides support for displaying the tab character (by overwriting `.cm-tab` class), I think it still makes sense if this add-on would support displaying the tab. The reason is that usually you want to provide an option that allows to user to toggle between showing or hiding whitespace characters. This is easier to implement if done programmatically by setting `showInvisibles` true/false than dynamically redefining the `.cm-tab` class.

Please add support for the tab character. And thanks for this nice little add-on for CodeMirror!

**Comment by coderaiser** [comment]
@twwwt I don't use tabs, and have no time for this unfortunately. But if you up for a PR, this would be great :).
